name: build and publish docker

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/386,linux/amd64,linux/arm64/v8,windows/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/bricklayers:latest
            ${{ secrets.DOCKERHUB_USER }}/bricklayers:${{github.ref_name}}